export const tabelData=
[
    {
        "Id": 1,
        
        "Status": "A",
        "CourseId": "2001",
        "CourseName": "Page Foundation",
        "CourseShortDesc": "In digital/agile transformation and product management, pages and forms are essential visual tools that represent digital products. Participants will learn how to effectively visualize, understand the interrelations of pages and forms, and use components to align with business requirements.",
        "CourseLongDesc": "In digital/agile transformation and digital product management, agile communication often flows through pages and forms, which serve as the visual representation of digital products. Participants will gain a deep understanding of page and form visualization, their interrelations, and how to utilize components effectively based on business requirements.",
        "OrderNo": 1,
        "FkCertificateId": "1,2,3,4,5,6",
        "IconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Circle-icons-computer.svg/768px-Circle-icons-computer.svg.png",
        "PdfUrl": "https://wellness.studentaffairs.miami.edu/_assets/pdf/cash-payment-receipt.pdf"
    },
    {
        "Id": 2,
        "Status": "A",
        "CourseId": "2002",
        "CourseName": "Product Requirement Analysis",
        "CourseShortDesc": "User acceptance criteria are vital in agile communication, providing a clear guide for what needs to be delivered, tested, and coded. Participants will learn to analyze product requirements and define precise acceptance criteria, ensuring clarity across business, research, and development teams.",
        "CourseLongDesc": "User acceptance criteria are crucial in agile communication. They serve as a guide, outlining what is required, what should be coded, tested, and ultimately delivered. Product requirement analysis helps business, research, and development teams define precise user acceptance criteria, enabling them to identify and address issues throughout the design, coding, and handover phases. Participants will learn how to effectively analyze product requirements, ensuring clear and actionable outcomes.",
        "OrderNo": 2,
        "FkCertificateId": "1,2,3,4,5,6",
        "IconUrl": "https://e7.pngegg.com/pngimages/237/899/png-clipart-business-plan-management-requirement-analysis-company-text.png",
        "PdfUrl": ""
    },
    {
        "Id": 3,
        "Status": "A",
        "CourseId": "2003",
        "CourseName": "Master Data Analysis",
        "CourseShortDesc": "Digital products rely on data, and understanding how data flows between systems is crucial for effective agile communication. Participants will gain the skills to articulate master data flow requirements, improving clarity and precision in short timeframes.",
        "CourseLongDesc": "The primary purpose of digital/agile transformation revolves around data—analytical reports, strategic analysis, performance measurement, AI, big data, and more. Digital products operate on data and the relationships between them (data flow). Understanding how data flows impact business operations, customer experience, and user engagement is critical for effective agile communication. Participants will learn how to articulate requirements in terms of master data flow, with clarity and precision, in a short time frame.",
        "OrderNo": 3,
        "FkCertificateId": "1,2,3,4,5,6",
        "IconUrl": "https://static.vecteezy.com/system/resources/thumbnails/027/396/319/small/analytics-reports-magnifier-and-report-icons-represent-data-analysis-and-reporting-ai-generated-png.png",
        "PdfUrl": ""
    },
    {
        "Id": 4,
        "Status": "A",
        "CourseId": "2004",
        "CourseName": "Fundamental SQL",
        "CourseShortDesc": "In agile communication, aligning business needs with technical implementation requires a strong understanding of data. This course teaches participants essential SQL skills to query, analyze, and manage data, enabling seamless communication and turning data-driven requirements into actionable insights.",
        "CourseLongDesc": "In agile communication, understanding data is vital for aligning business needs with technical implementation. This course equips participants with essential SQL skills to interact with databases effectively. Attendees will learn how to query, analyze, and manage data, enabling seamless communication between business and development teams by turning data-driven requirements into actionable insights.",
        "OrderNo": 4,
        "FkCertificateId": "2,3,5,6",
        "IconUrl": "https://cdn-icons-png.freepik.com/256/17266/17266017.png?semt=ais_hybrid",
        "PdfUrl": ""
    },
    {
        "Id": 5,
        "Status": "A",
        "CourseId": "2005",
        "CourseName": "Fundamental API",
        "CourseShortDesc": "APIs are central to agile communication, linking business needs with technical solutions. This course introduces participants to API fundamentals, teaching how to design and interpret APIs for clear, structured communication between systems and teams, boosting collaboration and efficiency in digital product management.\n\n",
        "CourseLongDesc": "APIs are the backbone of agile communication, connecting business needs with technical solutions. This course introduces participants to the core principles of APIs, including how they function, their role in digital products, and their importance in data exchange. Attendees will learn how to interpret and design APIs to ensure clear, structured communication between systems and teams, enhancing collaboration and efficiency in digital product management.",
        "OrderNo": 5,
        "FkCertificateId": "2,3,5,6",
        "IconUrl": "https://w7.pngwing.com/pngs/834/715/png-transparent-computer-icons-api-text-logo-desktop-wallpaper-thumbnail.png",
        "PdfUrl": ""
    },
    {
        "Id": 6,
        "Status": "A",
        "CourseId": "2006",
        "CourseName": "Digital Product Design",
        "CourseShortDesc": "Efficient data flow, database structure, and API design are essential for seamless digital product development and agile communication. This course empowers business representatives, researchers, and developers to align technical systems with business goals, ensuring optimized performance, scalability, and cross-functional collaboration.",
        "CourseLongDesc": "This comprehensive course delves into the critical elements of data flow design, database structuring, and API development, all essential for seamless digital product development and agile communication. Participants will master designing efficient data flows that align with business goals, optimize system performance, and enhance collaboration across teams. Emphasizing the importance of structured databases, the course teaches principles for clarity, scalability, and operational efficiency while bridging business needs with technical implementation. The API module focuses on creating clear, secure, and high-performing interfaces that foster smooth data exchange and integration. Business representatives, researchers, and development teams will gain practical skills to build robust systems tailored to organizational objectives. By fostering cross-functional alignment, this course equips participants to address real-world challenges in digital product ecosystems. Ultimately, teams will leave empowered to deliver innovative and scalable solutions through effective communication and collaboration.",
        "OrderNo": 6,
        "FkCertificateId": "2,3,5,6",
        "IconUrl": "https://cdn-icons-png.flaticon.com/512/7100/7100843.png",
        "PdfUrl": ""
    },
    {
        "Id": 7,
        "Status": "A",
        "CourseId": "2007",
        "CourseName": "Business Requirement Analysis",
        "CourseShortDesc": "Understanding business needs is crucial for successful digital products and agile communication. This course equips participants with the skills to analyze target audiences, segmentation, and data-driven challenges, helping them craft actionable requirements that bridge business goals with technical solutions for impactful digital products.\n",
        "CourseLongDesc": "Understanding business needs is the cornerstone of successful digital products and agile communication. This course equips participants with the skills to analyze target audiences, digital services, segmentation, and the data-driven challenges businesses face. Participants will explore how to assess competitors, identify unique advantages, and calculate the cost of addressing issues. By bridging the gap between business goals and technical solutions, this course ensures that teams can craft precise, actionable requirements that drive impactful digital products.",
        "OrderNo": 7,
        "FkCertificateId": "2,3,5,6",
        "IconUrl": "https://cdn-icons-png.flaticon.com/512/6655/6655980.png",
        "PdfUrl": ""
    },
    {
        "Id": 8,
        "Status": "A",
        "CourseId": "2008",
        "CourseName": "Financial Hypothesis Analysis",
        "CourseShortDesc": "In this course, participants will learn to build and assess financial hypotheses critical to digital product success. The course covers evaluating business models, estimating expenses and revenues, conducting risk analysis, and strategies for market entry, ensuring informed decision-making that maximizes value and minimizes risk in digital product development.\n",
        "CourseLongDesc": "In this course, participants will learn how to build and assess financial hypotheses critical for the success of digital products. The course covers how to determine the number of potential customers, evaluate business models, estimate expenses, revenues, and profits, and conduct risk analysis. Participants will also explore strategies for market entry, effective communication channels, and identifying financial drivers that influence decision-making. By mastering these financial fundamentals, participants will be equipped to make informed decisions that maximize value and minimize risk in digital product development.",
        "OrderNo": 8,
        "FkCertificateId": "2,3,5,6",
        "IconUrl": "https://cdn-icons-png.flaticon.com/512/12340/12340874.png",
        "PdfUrl": ""
    },
    {
        "Id": 9,
        "Status": "A",
        "CourseId": "2009",
        "CourseName": "Backlog Assessment",
        "CourseShortDesc": "Participants will learn how to assess and manage a product backlog using Agile Communication principles. The course focuses on prioritizing issues, managing sprints, estimating and tracking hours, calculating project duration, and managing budgets, ensuring alignment and effective resource allocation for successful project delivery.\n\n",
        "CourseLongDesc": "In this course, participants will learn how to assess and manage a product backlog using Agile Communication principles. By focusing on clear communication between teams, business stakeholders, and developers, attendees will understand how to prioritize issues, manage sprints, and allocate resources effectively. The course covers essential topics like estimating hours, tracking spent hours, calculating project duration, and managing budgets. Additionally, it will explore how to measure daily performance and assess development progress, ensuring that all stakeholders are aligned and informed. With a strong emphasis on Agile Communication, participants will be equipped to manage backlogs efficiently and ensure successful project delivery.",
        "OrderNo": 9,
        "FkCertificateId": "6",
        "IconUrl": "https://cdn-icons-png.flaticon.com/512/3516/3516721.png",
        "PdfUrl": ""
    },
    {
        "Id": 10,
        "Status": "A",
        "CourseId": "2010",
        "CourseName": "Project Management",
        "CourseShortDesc": "This course explores project management through Agile Communication, teaching techniques for issue management, sprint planning, and tracking spent hours. Participants will learn how to calculate project duration and budget, monitor team performance, and manage a comprehensive work breakdown, ensuring precise, collaborative, and successful project delivery.\n\n",
        "CourseLongDesc": "This course delves into the essential aspects of project management through the lens of Agile Communication. Participants will learn effective techniques for issue management, sprint planning, and tracking spent hours to ensure optimal project flow. The course covers critical topics like calculating project duration and budget, monitoring daily and development team performance, and structuring a comprehensive work breakdown. Attendees will also explore the classification of issue types and the handover process, ensuring seamless transitions and successful project delivery. By applying Agile Communication principles, this course equips participants to manage projects with precision, collaboration, and clarity",
        "OrderNo": 10,
        "FkCertificateId": "6",
        "IconUrl": "https://cdn-icons-png.freepik.com/256/12148/12148631.png?semt=ais_hybrid",
        "PdfUrl": ""
    },
    {
        "Id": 11,
        "Status": "A",
        "CourseId": "2011",
        "CourseName": "The Art and Skill of Sensing and Responding to Market Needs",
        "CourseShortDesc": "This course highlights agile communication as a key skill in responding to market demands. Participants will learn to analyze market dynamics, craft business models, and use data-driven insights to innovate for future opportunities while aligning with evolving market needs.\n",
        "CourseLongDesc": "This course explores agile communication as a pivotal skill in understanding and responding to market demands. Participants will learn to analyze market dynamics, craft effective business models, and identify data requirements to drive decisions. The course covers quantitative and qualitative methods for market analysis, digital service evaluation, and customer-centric insights. By mastering tools and techniques, attendees will develop the ability to innovate for future opportunities while aligning with evolving market needs.\n",
        "OrderNo": 11,
        "FkCertificateId": "3",
        "IconUrl": "https://cdn-icons-png.flaticon.com/256/7527/7527240.png",
        "PdfUrl": ""
    },
    {
        "Id": 12,
        "Status": "A",
        "CourseId": "2012",
        "CourseName": "Soft Skills in Management",
        "CourseShortDesc": "This course provides a foundation in essential soft skills for digital product management, covering decision-making, problem-solving, gap analysis, and conflict resolution. Participants will develop expertise in fostering collaboration through agile communication, ensuring efficient and effective management of digital product challenges.\n",
        "CourseLongDesc": "This course provides a comprehensive foundation in the soft skills crucial for success in digital product management. Participants will develop expertise in decision-making, defining key criteria, identifying alternatives, and applying effective management principles. The curriculum also covers critical problem-solving techniques, conducting gap analysis, conflict resolution strategies, and mastering the art of asking insightful questions. With a focus on agile communication, attendees will learn how to navigate complex challenges and foster collaboration across business, research, and development teams, ensuring efficient and effective product management.",
        "OrderNo": 12,
        "FkCertificateId": "6",
        "IconUrl": "https://e7.pngegg.com/pngimages/478/306/png-clipart-soft-skills-technology-engineer-science-technology-electronics-label-thumbnail.png\n",
        "PdfUrl": ""
    },
    {
        "Id": 13,
        "Status": "A",
        "CourseId": "2013",
        "CourseName": "Digital Services in Global Market",
        "CourseShortDesc": "This course offers an in-depth exploration of digital services through the lens of advanced technologies like AI, GenAI, blockchain, and big data. Participants will learn how to leverage information systems and communication technologies to foster collaboration and deliver innovative digital services on a global scale.",
        "CourseLongDesc": "This course offers a comprehensive exploration of digital services through the lens of information systems, internet technologies, and advanced tools like AI, GenAI, and blockchain. Participants will delve into the interplay between wired and wireless technologies, telecommunication, and knowledge management systems, while gaining insights into big data and machine learning (ML) applications. The curriculum emphasizes how agile communication fosters seamless collaboration between business, research, and development teams, ensuring innovative and efficient digital service delivery on a global scale.",
        "OrderNo": 13,
        "FkCertificateId": "4,5",
        "IconUrl": "https://cdn-icons-png.flaticon.com/512/3852/3852620.png",
        "PdfUrl": ""
    },
    {
        "Id": 14,
        "Status": "A",
        "CourseId": "2014",
        "CourseName": "Fundamental of AI/GenAI",
        "CourseShortDesc": "This course introduces the fundamentals of Artificial Intelligence (AI) and Generative AI (GenAI), exploring their impact on industries like business, manufacturing, fintech, and more. Participants will learn how these technologies are transforming sectors through automation, optimization, and innovation, providing foundational knowledge of AI/GenAI and their real-world applications.",
        "CourseLongDesc": "This course covers the fundamentals of Artificial Intelligence (AI) and Generative AI (GenAI), exploring their applications across various industries such as business, technology, manufacturing, fintech, and more. Participants will gain a solid understanding of how AI/GenAI technologies are transforming sectors like automation, hardware, software, and assembly. The course delves into the role of AI in digital transformation, providing insights into how these technologies enhance decision-making, optimize processes, and drive innovation in both technical and business environments. By the end, learners will understand the foundational principles of AI/GenAI and their practical applications in modern industries.",
        "OrderNo": 14,
        "FkCertificateId": "4,5",
        "IconUrl": "https://cdn-icons-png.freepik.com/512/7364/7364324.png",
        "PdfUrl": ""
    },
    {
        "Id": 15,
        "Status": "A",
        "CourseId": "2015",
        "CourseName": "Niche Segmentation with AI/GenAI",
        "CourseShortDesc": "Participants will explore the use of AI/GenAI in niche market segmentation, customer satisfaction, and sales strategies. The course covers leveraging AI for data-driven decision-making, analyzing customer behavior, and optimizing sales efforts, with hands-on practice in the DPMI Training Simulation System to apply AI/GenAI tools for business growth.\n",
        "CourseLongDesc": "This course focuses on the implementation of AI/GenAI technologies in niche market segmentation, customer satisfaction, and sales strategies. Participants will learn how to leverage AI/GenAI for data-driven decision-making, analyzing customer behavior, and optimizing sales strategies to target specific market segments effectively. The course will explore how AI and GenAI can transform customer insights, personalize marketing efforts, and drive business growth. Through hands-on practice in the DPMI Training Simulation System, participants will work with real-time data to gain practical experience in niche segmentation, data analysis, and improving customer satisfaction using advanced AI/GenAI tools.",
        "OrderNo": 15,
        "FkCertificateId": "5",
        "IconUrl": "https://cdn-icons-png.freepik.com/256/15565/15565304.png?semt=ais_hybrid",
        "PdfUrl": ""
    },
    {
        "Id": 16,
        "Status": "A",
        "CourseId": "2016",
        "CourseName": "AI/GenAI-driven Digital Services",
        "CourseShortDesc": "In this course, participants will learn how AI and Generative AI are revolutionizing digital services through automation and service enhancement. They will gain practical experience in implementing AI-driven solutions to improve operational efficiency, customer experience, and decision-making, using real-world examples and applications in sectors like finance, healthcare, and e-commerce.",
        "CourseLongDesc": "In this course, participants will explore the robotization of digital services through the integration of AI and Generative AI, building on the foundational knowledge provided in the \"Digital Services in Global Market\" course. The focus will be on how AI and GenAI technologies are transforming digital services, automating processes, and enhancing service delivery across industries. Participants will learn how to implement AI-driven solutions to improve operational efficiency, customer experience, and decision-making. Practical examples will cover AI-powered chatbots, virtual assistants, predictive analytics, and more, highlighting their application in various sectors, including finance, healthcare, e-commerce, and customer service. Participants will also practice real-world implementations in the DPMI Training Simulation System, gaining hands-on experience in developing AI/GenAI-driven digital services for the future of business.",
        "OrderNo": 16,
        "FkCertificateId": "5",
        "IconUrl": "https://www.antstack.com/assets/ai-ready/ai-eng.svg",
        "PdfUrl": ""
    }
]